---

- name: FLUENTD | Create fluentd group
  group:
    name: "{{ fluentd_group }}"
    state: present

- name: FLUENTD | Create fluentd user
  user:
    name: "{{ fluentd_user }}"
    group: "{{ fluentd_group }}"
    groups: "{{ fluentd_secondary_groups }}"

- name: FLUENTD | Install required libs
  apt:
    name: "{{ fluentd_required_libs }}"
    update_cache: yes

- name: FLUENTD | Install fluentd gem
  gem:
    name: fluentd
    state: present
    version: "{{ fluentd_version }}"
    user_install: no
  notify: restart fluentd

- name: FLUENTD | Install plugin required libs
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ fluentd_plugins_required_libs }}"

- name: FLUENTD | Install fluentd plugin gems
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
    user_install: no
  with_items: "{{ fluentd_plugins }}"
  notify: restart fluentd
